/**
 * Identifier unions generated from the StoneScript reference.
 *
 * @remarks
 * Extracted from {@link https://stonestoryrpg.com/stonescript/beta.html | the
 * Stonescript manual} (beta, v4.27.1 — 2026/01/15). Regenerate rather
 * than hand-edit when the game adds identifiers.
 *
 * Sets the game can extend are wrapped in {@link Loose} at the point of use,
 * so the documented values autocomplete while any other string is accepted.
 *
 * @packageDocumentation
 */

/**
 * Widens a literal union so unknown values are still accepted, without losing
 * autocompletion for the documented ones.
 *
 * @remarks
 * The `string & {}` half is what stops the editor collapsing the union down
 * to plain `string`.
 *
 * @typeParam T - The documented values.
 *
 * @example
 * ```ts
 * declare function play(sound: Loose<SoundId>): void;
 * play("bat_wing");   // autocompleted
 * play("new_sound");  // still allowed
 * ```
 */
export type Loose<T extends string> = T | (string & {});

/**
 * Ability cooldown ids, used by `item.GetCooldown` and the `activate` command.
 *
 * @see Appendix A of the Stonescript manual.
 */
export type AbilityId =
  | "bardiche"
  | "bash"
  | "blade"
  | "cinderwisp"
  | "dash"
  | "hatchet"
  | "heavy_hammer"
  | "lollipop_wand"
  | "mask"
  | "mind"
  | "quarterstaff"
  | "shovel"
  | "skeleton_arm"
  | "staff_aether"
  | "staff_fire"
  | "staff_ice"
  | "staff_poison"
  | "staff_stone"
  | "staff_vigor"
  | "talisman_aether"
  | "talisman_fire"
  | "voidweaver"
  | "wand_aether"
  | "wand_fire"
  | "wand_ice"
  | "wand_poison"
  | "wand_stone"
  | "wand_vigor";

/**
 * Sound effect ids, used by the `play` command.
 *
 * @see Appendix B of the Stonescript manual.
 */
export type SoundId =
  | "acronian_cultist_power_up"
  | "air_hiss"
  | "ant_attack"
  | "ant_death"
  | "ant_hill"
  | "ant_walk"
  | "auggie_voice"
  | "bang_go_forward"
  | "bardiche_cast"
  | "bat_attack"
  | "bat_attack_small"
  | "bat_death"
  | "bat_death_small"
  | "bat_wing"
  | "bat_wing_small"
  | "bearer3_talk"
  | "bearer4_talk"
  | "bearer4_talk_evolving"
  | "bearer5_talk"
  | "bearer_attack"
  | "bearer_attack_hit"
  | "bearer_death"
  | "bearer_evolving"
  | "bearer_scream"
  | "bearer_stealing"
  | "bearer_super_attack"
  | "bell_ringer_attack"
  | "bell_ringer_attack_hit"
  | "blade_drag"
  | "blade_glow"
  | "blade_pallas_attack"
  | "blade_raise"
  | "bomb_cart_explosion"
  | "bomb_cart_fuse"
  | "bomb_cart_move"
  | "boo_voice"
  | "booklet_close"
  | "booklet_open"
  | "booklet_turn_page"
  | "bronze_gate_close"
  | "bronze_gate_locked"
  | "bronze_gate_open"
  | "bronze_guardian_attack1"
  | "bronze_guardian_attack2"
  | "bronze_guardian_attack3"
  | "bronze_guardian_attack4"
  | "bronze_guardian_death"
  | "bronze_guardian_ears_ring"
  | "bronze_guardian_fuse"
  | "bronze_guardian_helmet"
  | "bronze_guardian_power_up"
  | "bronze_guardian_pulling_hammer"
  | "bronze_guardian_removing_hammer"
  | "bronze_guardian_steps"
  | "bronze_guardian_turbine"
  | "buy"
  | "click"
  | "confirm"
  | "controller_death"
  | "controller_whip_attack"
  | "controller_whip_hit"
  | "cross_deadwood_bump"
  | "cross_deadwood_row"
  | "cross_deadwood_splash"
  | "crossbow_cast"
  | "crossbow_hit"
  | "cult_guard_attack"
  | "cult_guard_attack_hit"
  | "cult_marksman_attack"
  | "cult_marksman_attack_hit"
  | "cult_sorcerer_attack"
  | "cult_sorcerer_attack_hit"
  | "cultist_death"
  | "devolved_talk"
  | "dog_bark"
  | "dominotaur_awake"
  | "dominotaur_death"
  | "dominotaur_whip_attack"
  | "dominotaur_whip_hit"
  | "dysangelos_guidance"
  | "dysangelos_guidance_1"
  | "dysangelos_guidance_2"
  | "dysangelos_guidance_3"
  | "dysangelos_intro_talk"
  | "elementalist_aether_attack"
  | "elementalist_aether_attack_hit"
  | "elementalist_aether_blink"
  | "elementalist_death"
  | "elementalist_evolving"
  | "elementalist_fire_attack"
  | "elementalist_fire_attack_hit"
  | "elementalist_fire_blink"
  | "elementalist_ice_attack"
  | "elementalist_ice_attack_hit"
  | "elementalist_ice_blink"
  | "elementalist_poison_attack"
  | "elementalist_poison_attack_hit"
  | "elementalist_poison_blink"
  | "elementalist_vigor_attack"
  | "elementalist_vigor_attack_hit"
  | "elementalist_vigor_blink"
  | "epilogue_devolving"
  | "epilogue_talk"
  | "epliogue_player_evolves"
  | "equip"
  | "error"
  | "falling_stonefolk"
  | "fire_beast_1"
  | "fire_beast_2"
  | "fire_elemental_attack"
  | "fire_elemental_attack_hit"
  | "fire_elemental_awake"
  | "fire_elemental_death"
  | "fire_geyser"
  | "fire_orbs"
  | "first_controller"
  | "fissure_break_apart"
  | "fissure_unmake"
  | "flying_serpent_loop"
  | "frog"
  | "ghost_attack"
  | "ghost_attack_small"
  | "ghost_death"
  | "ghost_death_small"
  | "ghost_loop"
  | "ghost_loop_small"
  | "ghost_tomb_death"
  | "giant_ice_elemental_attack"
  | "grappling_cast"
  | "grappling_hit"
  | "grappling_idle"
  | "hammer_cast"
  | "hammer_hit"
  | "hans_scream"
  | "hans_talk_intro"
  | "hans_talk_reward"
  | "hatchet_cast"
  | "hatchet_hit"
  | "haunted_gate_key_bounce_1"
  | "haunted_gate_key_bounce_2"
  | "haunted_gate_key_bounce_3"
  | "haunted_gate_key_into_gate"
  | "haunted_gate_npc_voice"
  | "haunted_gate_opening"
  | "haunted_gate_point_lost"
  | "haunted_gate_shuffle"
  | "haunted_gate_shuffle_fast"
  | "haunted_gate_torch_off"
  | "haunted_gate_torch_on"
  | "haunted_gate_try_to_open"
  | "ice_elemental_attack"
  | "ice_elemental_attack_hit"
  | "ice_elemental_awake"
  | "ice_elemental_death"
  | "ice_pillar"
  | "insta_kill"
  | "key_drop"
  | "ki_eater_attack"
  | "ki_eater_attack_hit"
  | "ki_eater_awake"
  | "ki_eater_death"
  | "ki_gobbler_attack"
  | "ki_gobbler_attack_hit"
  | "ki_gobbler_awake"
  | "ki_gobbler_death"
  | "ki_slerper_attack"
  | "ki_slerper_attack_hit"
  | "ki_slerper_awake"
  | "ki_slerper_death"
  | "ki_slerper_walk"
  | "level_up"
  | "life_gain"
  | "logo_full"
  | "logo_short"
  | "lost_item_boost"
  | "mask_summon_1"
  | "mask_summon_2"
  | "metal_drop"
  | "mindstone_found"
  | "mindstone_off"
  | "mindstone_on"
  | "mine_walker_attack_a"
  | "mine_walker_attack_b"
  | "mine_walker_attack_hit"
  | "mine_walker_awake"
  | "mine_walker_death"
  | "mine_walker_helmet_break"
  | "mine_walker_step"
  | "morel_punch"
  | "mosquito_attack"
  | "mosquito_death"
  | "mosquito_loop"
  | "mushroom_boss_awake"
  | "mushroom_boss_death"
  | "mushroom_boss_fat_slam"
  | "mushroom_boss_punch"
  | "mushroom_boss_shoot"
  | "mushroom_boss_split"
  | "nagaraja_attack_eat"
  | "nagaraja_attack_lick"
  | "nagaraja_attack_swallow"
  | "nagaraja_awake_roar"
  | "nagaraja_awake_swallow"
  | "nagaraja_awake_tongue_1"
  | "nagaraja_awake_tongue_2"
  | "nagaraja_choir"
  | "nagaraja_dead"
  | "nagaraja_poison_attack"
  | "nagaraja_poison_attack_hit"
  | "nagaraja_tongue_damaged"
  | "nagaraja_tongue_lift"
  | "nagaraja_tongue_smell"
  | "nagaraja_tongue_wrap"
  | "nagaraja_wail"
  | "nagaraja_wail_brick"
  | "open_note"
  | "paint_splat"
  | "pallas_voice"
  | "perfected_attack"
  | "perfected_attack_hit"
  | "perfected_death"
  | "perfected_defense"
  | "perfected_energy_ball"
  | "perfected_energy_ball_hit"
  | "perfected_fly_end"
  | "perfected_fly_loop"
  | "perfected_fly_start"
  | "perfected_summon"
  | "perfected_talk"
  | "pickup_bronze"
  | "pickup_stone"
  | "pickup_success"
  | "pickup_tar"
  | "pickup_wood"
  | "player_death"
  | "player_hit"
  | "player_kick"
  | "player_punch"
  | "poison_adept_attack"
  | "poison_adept_attack_hit"
  | "poison_powerup"
  | "potion_berserk"
  | "potion_cleansing"
  | "potion_defensive"
  | "potion_experience"
  | "potion_healing"
  | "potion_invisibility"
  | "potion_lightning"
  | "potion_lucky"
  | "potion_strength"
  | "potion_vampiric"
  | "progress_1"
  | "progress_2"
  | "progress_3"
  | "progress_4"
  | "progress_5"
  | "progress_6"
  | "progress_7"
  | "progress_8"
  | "progress_9"
  | "prompt_choice"
  | "quarterstaff_cast"
  | "quest_stone_jump"
  | "quest_stone_unlock"
  | "ranting_tree_halt"
  | "ranting_tree_talk_again"
  | "ranting_tree_talk_avenge"
  | "ranting_tree_talk_extra"
  | "ranting_tree_talk_get_out"
  | "ranting_tree_talk_halt"
  | "ranting_tree_talk_how_dare"
  | "ranting_tree_talk_impressive"
  | "ranting_tree_talk_very_well"
  | "scarab_awake"
  | "scarab_bite"
  | "scarab_death"
  | "scarab_horn"
  | "scarab_wings"
  | "scorpion_death"
  | "scotty_a_pleasure"
  | "scotty_a_worthy_opponent"
  | "scotty_deuced"
  | "scotty_failte_back"
  | "scotty_getting_good"
  | "scotty_grr"
  | "scotty_guess_which"
  | "scotty_hell_be_back"
  | "scotty_intro"
  | "scotty_lets_harden"
  | "scotty_make_ye_guess"
  | "scotty_noo_jist"
  | "scotty_out_of_treasure"
  | "scotty_perhaps_the_rules"
  | "scotty_pick_some_treasure"
  | "scotty_shall_we_up"
  | "scotty_there_he_is"
  | "scotty_we_have_wee_use"
  | "scotty_well_met"
  | "scotty_well_then"
  | "scotty_wizard"
  | "scotty_wrong_choice"
  | "scout_arrives"
  | "scout_dialog"
  | "scout_focus"
  | "scout_leaves"
  | "scout_wing"
  | "serpent_attack"
  | "serpent_death"
  | "serpent_handler_release"
  | "serpent_hiss"
  | "serpent_slither"
  | "shield_dash"
  | "shop_door_enter"
  | "shop_door_open"
  | "shovel_cast"
  | "sightstone_cast"
  | "skeletimmy_attack"
  | "skeletimmy_death"
  | "skeleton_boss_arm1"
  | "skeleton_boss_arm2"
  | "skeleton_boss_arm_reconnect"
  | "skeleton_boss_arm_woosh"
  | "skeleton_boss_attack"
  | "skeleton_boss_awake"
  | "skeleton_boss_bone_bounce"
  | "skeleton_boss_death"
  | "skeleton_boss_hand_slam"
  | "skeleton_boss_idle"
  | "skeleton_boss_legs_die"
  | "skeleton_boss_summon_minions"
  | "skeletony_attack"
  | "skeletony_awake_a"
  | "skeletony_awake_b"
  | "skeletony_death"
  | "skeletony_walk"
  | "slave_npc"
  | "slave_outro_chatter"
  | "slave_outro_transition"
  | "slave_outro_voice"
  | "smithy_hammer"
  | "smithy_hammer_fail"
  | "snail_attack"
  | "snail_attack_small"
  | "snail_death"
  | "snail_death_small"
  | "snail_walk"
  | "soul_stone"
  | "soul_stone_drop"
  | "spider_attack"
  | "spider_boss_attack"
  | "spider_boss_awake"
  | "spider_boss_death"
  | "spider_death"
  | "spider_death_small"
  | "spider_eggs_spawn"
  | "spider_walk"
  | "stone_throw_cast"
  | "stone_throw_hit"
  | "sword_cast"
  | "sword_hit"
  | "talisman_reveal"
  | "temple_npc_chant"
  | "temple_npc_clear_throat"
  | "temple_npc_talk"
  | "torch_cast"
  | "torch_hit"
  | "torch_idle"
  | "treasure_close"
  | "treasure_drop"
  | "treasure_drop_common"
  | "treasure_drop_epic"
  | "treasure_drop_giant"
  | "treasure_drop_humble"
  | "treasure_drop_rare"
  | "treasure_item_blue"
  | "treasure_item_cyan"
  | "treasure_item_green"
  | "treasure_item_lost"
  | "treasure_item_pop"
  | "treasure_item_rainbow"
  | "treasure_item_red"
  | "treasure_item_show"
  | "treasure_item_yellow"
  | "treasure_open"
  | "tree_boss_attack"
  | "tree_boss_awake"
  | "tree_boss_death"
  | "tree_boss_idle"
  | "tree_boss_spike"
  | "triskelion_fuse"
  | "ui_starfirst"
  | "ui_starnew"
  | "ui_starold1"
  | "ui_starold2"
  | "ui_starold3"
  | "ui_starold4"
  | "unequip"
  | "uulaa_voice"
  | "wand_aether_cast"
  | "wand_aether_hit"
  | "wand_air_cast"
  | "wand_air_hit"
  | "wand_cast"
  | "wand_drop"
  | "wand_fire_cast"
  | "wand_fire_hit"
  | "wand_hit"
  | "wand_ice_cast"
  | "wand_ice_hit"
  | "wand_poison_cast"
  | "wand_poison_hit"
  | "wand_vigor_cast"
  | "wand_vigor_hit"
  | "waterfall_hook_hit"
  | "waterfall_land"
  | "waterfall_rope_grab"
  | "waterfall_rope_swing"
  | "waterfall_splash"
  | "worm_rider_hop"
  | "xp_tick"
  | "yeti_attack"
  | "yeti_attack_flick"
  | "yeti_attack_hit"
  | "yeti_awake_blow"
  | "yeti_awake_explosion"
  | "yeti_awake_inhale"
  | "yeti_awake_lick"
  | "yeti_blow"
  | "yeti_blow_ice_wall"
  | "yeti_death"
  | "yeti_inhale"
  | "yeti_inhale_lick";

/**
 * Music track ids, used by `music.Play`.
 *
 * @see Appendix C of the Stonescript manual.
 */
export type MusicId =
  | "bronze_guardian_3"
  | "bronze_guardian_4"
  | "bronze_guardian_5"
  | "bronze_guardian_cyan"
  | "bronze_mine_0"
  | "bronze_mine_1"
  | "bronze_mine_2"
  | "bronze_mine_3"
  | "bronze_mine_4"
  | "bronze_mine_5"
  | "bronze_mine_cyan"
  | "slave_outro_climb"
  | "slave_outro_loop"
  | "caustic_caves"
  | "spider_boss"
  | "cross_deadwood_river"
  | "cross_deadwood_wind"
  | "deadwood_0"
  | "deadwood_1"
  | "deadwood_2"
  | "deadwood_3"
  | "deadwood_4"
  | "deadwood_5"
  | "deadwood_cyan"
  | "tree_boss"
  | "waterfall_descent"
  | "poena"
  | "skeleton_boss"
  | "undead_crypt_0"
  | "undead_crypt_1"
  | "undead_crypt_2"
  | "undead_crypt_3"
  | "undead_crypt_4"
  | "undead_crypt_5"
  | "undead_crypt_cyan"
  | "undead_crypt_intro"
  | "bridge_broken"
  | "bridge_crossing"
  | "icy_ridge_0"
  | "icy_ridge_1"
  | "icy_ridge_2"
  | "icy_ridge_3"
  | "icy_ridge_4"
  | "icy_ridge_5"
  | "icy_ridge_cyan"
  | "yeti"
  | "fire_loop"
  | "fungus_forest_0"
  | "fungus_forest_1"
  | "fungus_forest_2"
  | "fungus_forest_3"
  | "fungus_forest_4"
  | "fungus_forest_5"
  | "fungus_forest_cyan"
  | "mushroom_boss"
  | "mushroom_boss_cyan"
  | "shop"
  | "rocky_plateau_0"
  | "rocky_plateau_1"
  | "rocky_plateau_2"
  | "rocky_plateau_3"
  | "rocky_plateau_4"
  | "rocky_plateau_5"
  | "rocky_plateau_epilogue"
  | "rocky_plateau_fight"
  | "rocky_plateau_talk"
  | "nagaraja"
  | "temple_0"
  | "temple_1"
  | "temple_2"
  | "temple_3"
  | "temple_4"
  | "temple_5"
  | "temple_cyan"
  | "event_fall"
  | "event_hamartia"
  | "event_spring"
  | "event_stonejam"
  | "event_summer"
  | "event_winter"
  | "credits"
  | "main_menu"
  | "bone_factory"
  | "osteophone"
  | "uulaa";

/**
 * Ambient audio loop ids, used by `ambient.Add`.
 *
 * @see Appendix D of the Stonescript manual.
 */
export type AmbientId =
  | "ambient_mines"
  | "ambient_caves"
  | "ambient_bronze_gate"
  | "ambient_deadwood"
  | "ambient_mushroom"
  | "ambient_bridge"
  | "ambient_icy"
  | "ambient_cave"
  | "ambient_rocky"
  | "ambient_temple"
  | "ambient_crypt"
  | "ambient_haunted_gate"
  | "ambient_pallas"
  | "waterfall_a"
  | "waterfall_b"
  | "waterfall_c";

/**
 * Bindable input actions, used by the `key` namespace.
 *
 * @remarks
 * A closed set: the game defines exactly these actions.
 */
export type KeyAction =
  | "Pause"
  | "Leave"
  | "Inventory"
  | "Mindstone"
  | "Potion"
  | "ItemLeft"
  | "ItemRight"
  | "Up"
  | "Down"
  | "Left"
  | "Right"
  | "Primary"
  | "Back"
  | "Ability1"
  | "Ability2"
  | "BumpL"
  | "BumpR"
  | "Dynamic1"
  | "Dynamic2"
  | "Dynamic3"
  | "Dynamic4"
  | "Dynamic5";

/**
 * Key names the manual lists as defaults.
 *
 * @remarks
 * Key names follow the engine's own naming, so this is the documented subset
 * rather than every accepted value — use it through {@link Loose}.
 */
export type KeyName =
  | "P"
  | "Space"
  | "L"
  | "I"
  | "M"
  | "Q"
  | "E"
  | "R"
  | "W"
  | "UpArrow"
  | "S"
  | "DownArrow"
  | "A"
  | "LeftArrow"
  | "D"
  | "RightArrow"
  | "Return"
  | "KeypadEnter"
  | "X"
  | "LeftShift"
  | "RightShift"
  | "LeftControl"
  | "RightControl"
  | "Z"
  | "C"
  | "F"
  | "T"
  | "G"
  | "V"
  | "B";

/**
 * Tags accepted by the item and foe search filters.
 *
 * @see The Search Filters section of the Stonescript manual.
 */
export type SearchFilter =
  | "poison"
  | "vigor"
  | "aether"
  | "fire"
  | "air"
  | "ice"
  | "arachnid"
  | "serpent"
  | "insect"
  | "machine"
  | "humanoid"
  | "elemental"
  | "boss"
  | "phase1"
  | "phase2"
  | "phase3"
  | "spawner"
  | "flying"
  | "slow"
  | "ranged"
  | "explode"
  | "swarm"
  | "unpushable"
  | "undamageable"
  | "magic_resist"
  | "magic_vulnerability"
  | "immune_to_stun"
  | "immune_to_ranged"
  | "immune_to_debuff_damage"
  | "immune_to_physical";
